import React, { createContext, useContext, useMemo, useState } from 'react';

export type Language = 'en' | 'ta' | 'hi';
type Dictionary = Record<string, string>;

const en: Dictionary = {
  langLabel: 'Language',
  dashboard: 'Dashboard',
  assets: 'Assets',
  procurement: 'Procurement',
  labs: 'Labs',
  users: 'Users',
  maintenance: 'Maintenance',
  reports: 'Reports',
  settings: 'Settings',
  myAssets: 'My Assets',
  maintenanceRequests: 'Maintenance Requests',
  assignedTasks: 'Assigned Tasks',
  purchaseDeptOrders: 'Purchase Department Orders',
  signIn: 'Sign In',
  register: 'Register',
  logout: 'Logout',
  modules: 'MODULES',
  account: 'ACCOUNT',
  searchAssets: 'Search assets...',
  notifications: 'Notifications',
  clear: 'Clear',
  noNewNotifications: 'No new notifications.',
  notifWarrantyExpiring: '3 assets are nearing warranty expiry.',
  notifTasksCompleted: '2 maintenance tasks were completed.',
  notifNewProcurement: 'New procurement request submitted.',

  totalAssets: 'Total Assets',
  activeAssets: 'Active Assets',
  damagedAssets: 'Damaged Assets',
  pendingRequests: 'Pending Requests',
  totalUsers: 'Total Users',
  adminDashboard: 'Admin Dashboard',
  adminOverview: "Welcome back. Here's your complete campus overview.",
  assetsByLocation: 'Assets by Location',
  categoryDistribution: 'Asset Category Distribution',
  monthlyTrend: 'Monthly Procurement Trend (INR)',
  trendPrepared: 'Trend data prepared',
  trendPreparedDesc: 'Connect backend procurement analytics to render this chart with live values.',
  fromLastMonth: '+12% from last month',
  csLabs: 'CS Labs',
  electronicsLab: 'Electronics Lab',
  library: 'Library',
  classrooms: 'Classrooms',
  auditorium: 'Auditorium',
  gymnasium: 'Gymnasium',
  serverRoom: 'Server Room',
  admin: 'Admin',
  Computer: 'Computer',
  'Lab Equipment': 'Lab Equipment',
  Network: 'Network',

  assetManagement: 'Asset Management',
  viewManageLabAssets: 'View and manage your lab assets',
  exportCsv: 'Export CSV',
  searchByNameCode: 'Search by name or code...',
  allCategories: 'All Categories',
  allStatus: 'All Status',
  assetRegister: 'Asset Register',
  adminAssetRegisterSubtitle: 'Admin can add, edit, delete, and assign lab ownership',
  assetCode: 'Asset Code',
  asset: 'Asset',
  category: 'Category',
  location: 'Location',
  status: 'Status',
  warranty: 'Warranty',
  actions: 'Actions',
  edit: 'Edit',
  assignLab: 'Assign Lab',
  delete: 'Delete',
  error: 'Error',
  Active: 'Active',
  Damaged: 'Damaged',
  'Under Maintenance': 'Under Maintenance',
  Pending: 'Pending',
  Completed: 'Completed',
  Borrowed: 'Borrowed',
  Returned: 'Returned',
  'Late Return': 'Late Return',
  'In Progress': 'In Progress',
  'Pending Admin Approval': 'Pending Admin Approval',
  'Approved by Admin': 'Approved by Admin',
  'Sent to Purchase Dept': 'Sent to Purchase Dept',
  'Accepted by Purchase Dept': 'Accepted by Purchase Dept',
  'Rejected by Purchase Dept': 'Rejected by Purchase Dept',
  Assigned: 'Assigned',

  procurementCenter: 'Procurement Command Center',
  procurementCenterDesc: 'Approve lab requests and route to purchase department with separate Purchase and Service controls.',
  purchaseRequests: 'Purchase Requests',
  serviceRequests: 'Service Requests',
  all: 'All',
  purchase: 'Purchase',
  service: 'Service',
  labRequests: 'Lab Requests',
  adminProcurementSubtitle: 'Admin acceptance and purchase department routing workflow',
  requestNo: 'Request No',
  requestedBy: 'Requested By',
  date: 'Date',
  purchaseDepartment: 'Purchase Department',
  approve: 'Approve',
  sendToPurchaseDept: 'Send to Purchase Dept',
  request: 'Request',
  type: 'Type',

  maintenanceControl: 'Maintenance Control',
  maintenanceControlSubtitle: 'Admin assignment and request triage',
  requestId: 'Request ID',
  assignedTo: 'Assigned To',
  unassigned: 'Unassigned',
  priority: 'Priority',
  assignService: 'Assign Service',

  borrowingReports: 'Borrowing & Invoice Reports',
  borrowingReportsDesc: 'Save and download bill, invoice, product, warranty, issue updates, and penalties as PDF.',
  borrowingReportsTable: 'Borrowing Reports',
  borrowingReportsTableDesc: 'Admin level compliance and audit export',
  borrowId: 'Borrow ID',
  student: 'Student',
  project: 'Project',
  bill: 'Bill',
  invoice: 'Invoice',
  penalty: 'Penalty',
  download: 'Download',
  pdf: 'PDF',
  issueUpdates: 'Issue Updates',

  labsTitle: 'Lab',
  labsSubtitle: 'Lab directory and ownership overview',
  labName: 'Lab Name',
  department: 'Department',
  assetCount: 'Asset Count',
  incharge: 'Incharge',

  usersTitle: 'Users',
  usersSubtitle: 'Role assignments and lab mapping',
  name: 'Name',
  role: 'Role',
  email: 'Email',
  assignedLab: 'Assigned Lab',

  labDashboard: 'Lab Dashboard',
  labOverview: 'Lab-specific asset and maintenance overview.',
  active: 'Active',
  pending: 'Pending',
  critical: 'Critical',
  damaged: 'Damaged',
  underMaintenance: 'Under Maintenance',

  studentBorrowingDesk: 'Student Borrowing Desk',
  studentBorrowingDesc: 'Issue electronics to students for project development with bill/invoice and downloadable PDF records.',
  studentName: 'Student Name',
  projectName: 'Project Name',
  returnDueDate: 'Return Due Date',
  generateBorrowBill: 'Generate Borrow Bill',
  borrowCart: 'Borrow Cart',
  total: 'Total',
  noProductsSelected: 'No products selected.',
  electronicsCatalog: 'Electronics Catalog',
  electronicsCatalogDesc: 'Lab stock available for student projects',
  borrowRegister: 'Borrow Register',
  borrowRegisterDesc: 'Bill, invoice, product, warranty, issue updates, and penalties',
  product: 'Product',
  unitCost: 'Unit Cost',
  inStock: 'In Stock',
  action: 'Action',
  addToBorrowCart: 'Add to Borrow Cart',
  return: 'Return',
  enterStudentDetails: 'Enter student details, due date, and at least one product.',
  borrowCreated: 'Borrow request created with bill and invoice details.',
  noIssueUpdates: 'No issue updates',
  notReturnedYet: 'Not returned yet',
  productDetails: 'Product Details',
  returnedDate: 'Returned Date',
  finePenalty: 'Fine/Penalty',
  totalValue: 'Total Value',
  months: 'months',
  qty: 'Qty',

  maintenanceTitle: 'Maintenance',
  maintenanceDesc: 'View and raise maintenance requests',
  reportIssue: 'Report Issue',
  quickScan: 'Quick Scan',
  scanAssetQr: 'Scan Asset QR Code',
  qrDesc: "Point your device camera at the asset's QR code to quickly log a maintenance issue.",
  openScanner: 'Open Scanner',
  maintenanceLog: 'Maintenance Log',
  maintenanceLogDesc: 'Lab request history and current statuses',
  maintenanceHistory: 'Maintenance History',
  maintenanceHistoryDesc: 'Status timeline for all requests',
  issue: 'Issue',
  reportedBy: 'Reported By',
  noLabAssetsForRequest: 'No lab assets available to raise a request.',
  maintenanceRequestCreated: 'Maintenance request created.',

  assetRequirementRequests: 'Asset Requirement Requests',
  assetRequirementDesc: 'Visit requirements, add to cart, and submit purchase/service requests to admin.',
  requestType: 'Request Type',
  notes: 'Notes',
  requirementNotes: 'Requirement notes',
  submitToAdmin: 'Submit to Admin',
  requirementCart: 'Requirement Cart',
  noRequirementsSelected: 'No requirements selected.',
  requirementCatalog: 'Requirement Catalog',
  requirementCatalogDesc: 'Electronics and service entries for requisition',
  myRequests: 'My Requests',
  myRequestsDesc: 'Track approval and purchase department status from admin',
  requirementItem: 'Requirement Item',
  estimatedCost: 'Estimated Cost',
  stock: 'Stock',
  addToCart: 'Add to Cart',
  atLeastOneRequirement: 'Add at least one requirement to cart.',
  requirementSubmitted: 'Requirement request submitted to admin.',

  serviceDashboard: 'Service Dashboard',
  serviceOverview: 'Assigned maintenance workload and completion tracking.',
  inProgress: 'In Progress',
  completed: 'Completed',
  serviceTasksTitle: 'Service Tasks',
  serviceTasksDesc: 'Pending and active requests assigned to service staff',
  assignedTasksTitle: 'Assigned Tasks',
  assignedTasksDesc: 'Service staff can update maintenance status and add remarks only.',
  closed: 'Closed',
  mark: 'Mark',

  purchaseDeptPortal: 'Purchase Department Portal',
  purchaseDeptPortalDesc: 'Review approved purchase/service requests from admin and accept them for fulfillment.',
  assignedOrders: 'Assigned Orders',
  purchaseDeptWorkflowDesc: 'Purchase Department acceptance workflow',
  accept: 'Accept',
  reject: 'Reject',

  settingsTitle: 'Settings',
  settingsDesc: 'Manage your system preferences',
  general: 'General',
  institutionName: 'Institution Name',
  adminEmail: 'Admin Email',
  notificationsTitle: 'Notifications',
  notifProcurement: 'Email notifications for new procurement requests',
  notifWarranty: 'Warranty expiry alerts (30 days before)',
  notifMaintenance: 'Maintenance status updates',
  notifWeekly: 'Weekly asset summary report',
  security: 'Security',
  twoFactor: 'Two-factor authentication',
  sessionTimeout: 'Session timeout (30 min)',
  data: 'Data',
  exportAllData: 'Export all data',
  exportAllDataDesc: 'Download complete asset database as CSV',
  export: 'Export',
  resetDemoData: 'Reset Demo Data',
  resetDemoDataDesc: 'Restore all data to default state',
  reset: 'Reset',
  saveChanges: 'Save Changes',
  settingsExported: 'Settings exported successfully.',
  settingsReset: 'Settings reset to defaults.',
  settingsSaved: 'Settings saved.',
  searchRecords: 'Search records',
  searchRecordsEllipsis: 'Search records...',
  noRecordsFound: 'No records found',
  adjustSearchFilter: 'Try adjusting your search or filter criteria.',
  searchList: 'Search list',
  searchListEllipsis: 'Search list...',
  noListItems: 'No list items',
  noMatchingListEntries: 'There are no matching entries for this list.'
};

const ta: Dictionary = {
  ...en,
  langLabel: 'மொழி',
  dashboard: 'டாஷ்போர்டு',
  assets: 'சொத்துகள்',
  procurement: 'கொள்முதல்',
  labs: 'ஆய்வகங்கள்',
  users: 'பயனர்கள்',
  maintenance: 'பராமரிப்பு',
  reports: 'அறிக்கைகள்',
  settings: 'அமைப்புகள்',
  myAssets: 'என் சொத்துகள்',
  maintenanceRequests: 'பராமரிப்பு கோரிக்கைகள்',
  assignedTasks: 'ஒதுக்கப்பட்ட பணிகள்',
  purchaseDeptOrders: 'ଵிற்பனையாளர் ஆர்டர்கள்',
  signIn: 'உள்நுழைவு',
  register: 'பதிவு',
  logout: 'வெளியேறு',
  modules: 'தொகுதிகள்',
  account: 'கணக்கு',
  searchAssets: 'சொத்துகளை தேடவும்...',
  notifications: 'அறிவிப்புகள்',
  clear: 'அழி',
  noNewNotifications: 'புதிய அறிவிப்புகள் இல்லை.',
  totalAssets: 'மொத்த சொத்துகள்',
  activeAssets: 'செயலில் உள்ள சொத்துகள்',
  damagedAssets: 'சேதமடைந்த சொத்துகள்',
  pendingRequests: 'நிலுவை கோரிக்கைகள்',
  totalUsers: 'மொத்த பயனர்கள்',
  adminDashboard: 'நிர்வாக டாஷ்போர்டு',
  assetManagement: 'சொத்து மேலாண்மை',
  exportCsv: 'CSV ஏற்றுமதி',
  allCategories: 'அனைத்து வகைகள்',
  allStatus: 'அனைத்து நிலைகள்',
  status: 'நிலை',
  actions: 'செயல்கள்',
  edit: 'திருத்து',
  delete: 'நீக்கு',
  purchase: 'கொள்முதல்',
  service: 'சேவை',
  requestNo: 'கோரிக்கை எண்',
  requestedBy: 'கோரியவர்',
  date: 'தேதி',
  purchaseDepartment: 'ଵிற்பனையாளர்',
  approve: 'அனுமதி',
  requestId: 'கோரிக்கை ஐடி',
  priority: 'முன்னுரிமை',
  assignService: 'சேவைக்கு ஒதுக்கு',
  student: 'மாணவர்',
  project: 'திட்டம்',
  bill: 'பில்',
  invoice: 'இன்வாய்ஸ்',
  penalty: 'அபராதம்',
  download: 'பதிவிறக்கு',
  labName: 'ஆய்வக பெயர்',
  department: 'துறை',
  assetCount: 'சொத்து எண்ணிக்கை',
  name: 'பெயர்',
  role: 'பங்கு',
  email: 'மின்னஞ்சல்',
  assignedLab: 'ஒதுக்கப்பட்ட ஆய்வகம்',
  labDashboard: 'ஆய்வக டாஷ்போர்டு',
  active: 'செயலில்',
  pending: 'நிலுவையில்',
  critical: 'முக்கியம்',
  damaged: 'சேதம்',
  underMaintenance: 'பராமரிப்பில்',
  studentName: 'மாணவர் பெயர்',
  projectName: 'திட்ட பெயர்',
  returnDueDate: 'திருப்ப வேண்டிய தேதி',
  total: 'மொத்தம்',
  product: 'தயாரிப்பு',
  category: 'வகை',
  warranty: 'உத்தரவாதம்',
  inStock: 'இருப்பு',
  action: 'நடவடிக்கை',
  return: 'திருப்பு',
  maintenanceTitle: 'பராமரிப்பு',
  reportIssue: 'சிக்கலை பதிவு செய்',
  quickScan: 'விரைவு ஸ்கேன்',
  issue: 'சிக்கல்',
  reportedBy: 'பதிவுசெய்தவர்',
  notes: 'குறிப்புகள்',
  submitToAdmin: 'நிர்வாகிக்கு அனுப்பு',
  serviceDashboard: 'சேவை டாஷ்போர்டு',
  inProgress: 'செயல்பாட்டில்',
  completed: 'முடிந்தது',
  closed: 'மூடப்பட்டது',
  accept: 'ஏற்கவும்',
  reject: 'நிராகரி',
  settingsTitle: 'அமைப்புகள்',
  general: 'பொது',
  institutionName: 'நிறுவன பெயர்',
  adminEmail: 'நிர்வாகி மின்னஞ்சல்',
  security: 'பாதுகாப்பு',
  data: 'தரவு',
  export: 'ஏற்றுமதி',
  reset: 'மீட்டமை',
  saveChanges: 'மாற்றங்களை சேமி',
  qty: 'அளவு',
  months: 'மாதங்கள்',
  notifWarrantyExpiring: '3 சொத்துகள் உத்தரவாதம் முடிவடைய உள்ளது.',
  notifTasksCompleted: '2 பராமரிப்பு பணிகள் முடிக்கப்பட்டன.',
  notifNewProcurement: 'புதிய கொள்முதல் கோரிக்கை சமர்ப்பிக்கப்பட்டது.'
};

const hi: Dictionary = {
  ...en,
  langLabel: 'भाषा',
  dashboard: 'डैशबोर्ड',
  assets: 'एसेट्स',
  procurement: 'प्रोक्योरमेंट',
  labs: 'लैब्स',
  users: 'यूज़र्स',
  maintenance: 'मेंटेनेंस',
  reports: 'रिपोर्ट्स',
  settings: 'सेटिंग्स',
  myAssets: 'मेरे एसेट्स',
  maintenanceRequests: 'मेंटेनेंस अनुरोध',
  assignedTasks: 'असाइन्ड टास्क्स',
  purchaseDeptOrders: 'वेंडर ऑर्डर्स',
  signIn: 'साइन इन',
  register: 'रजिस्टर',
  logout: 'लॉगआउट',
  modules: 'मॉड्यूल्स',
  account: 'अकाउंट',
  searchAssets: 'एसेट्स खोजें...',
  notifications: 'नोटिफिकेशन्स',
  clear: 'साफ करें',
  noNewNotifications: 'कोई नया नोटिफिकेशन नहीं।',
  totalAssets: 'कुल एसेट्स',
  activeAssets: 'सक्रिय एसेट्स',
  damagedAssets: 'डैमेज्ड एसेट्स',
  pendingRequests: 'लंबित अनुरोध',
  totalUsers: 'कुल यूज़र्स',
  adminDashboard: 'एडमिन डैशबोर्ड',
  assetManagement: 'एसेट मैनेजमेंट',
  exportCsv: 'CSV एक्सपोर्ट',
  allCategories: 'सभी कैटेगरी',
  allStatus: 'सभी स्टेटस',
  status: 'स्थिति',
  actions: 'कार्य',
  edit: 'एडिट',
  delete: 'डिलीट',
  purchase: 'खरीद',
  service: 'सेवा',
  requestNo: 'रिक्वेस्ट नंबर',
  requestedBy: 'रिक्वेस्ट करने वाला',
  date: 'तारीख',
  purchaseDepartment: 'वेंडर',
  approve: 'स्वीकृत करें',
  requestId: 'रिक्वेस्ट आईडी',
  priority: 'प्राथमिकता',
  assignService: 'सर्विस असाइन करें',
  student: 'छात्र',
  project: 'प्रोजेक्ट',
  bill: 'बिल',
  invoice: 'इनवॉइस',
  penalty: 'जुर्माना',
  download: 'डाउनलोड',
  labName: 'लैब नाम',
  department: 'विभाग',
  assetCount: 'एसेट संख्या',
  name: 'नाम',
  role: 'भूमिका',
  email: 'ईमेल',
  assignedLab: 'असाइन्ड लैब',
  labDashboard: 'लैब डैशबोर्ड',
  active: 'सक्रिय',
  pending: 'लंबित',
  critical: 'गंभीर',
  damaged: 'क्षतिग्रस्त',
  underMaintenance: 'मेंटेनेंस में',
  studentName: 'छात्र नाम',
  projectName: 'प्रोजेक्ट नाम',
  returnDueDate: 'वापसी नियत तिथि',
  total: 'कुल',
  product: 'प्रोडक्ट',
  category: 'कैटेगरी',
  warranty: 'वारंटी',
  inStock: 'स्टॉक',
  action: 'कार्य',
  return: 'वापसी',
  maintenanceTitle: 'मेंटेनेंस',
  reportIssue: 'समस्या रिपोर्ट करें',
  quickScan: 'क्विक स्कैन',
  issue: 'समस्या',
  reportedBy: 'रिपोर्ट करने वाला',
  notes: 'नोट्स',
  submitToAdmin: 'एडमिन को भेजें',
  serviceDashboard: 'सर्विस डैशबोर्ड',
  inProgress: 'प्रगति में',
  completed: 'पूर्ण',
  closed: 'बंद',
  accept: 'स्वीकार',
  reject: 'अस्वीकार',
  settingsTitle: 'सेटिंग्स',
  general: 'सामान्य',
  institutionName: 'संस्थान नाम',
  adminEmail: 'एडमिन ईमेल',
  security: 'सुरक्षा',
  data: 'डेटा',
  export: 'एक्सपोर्ट',
  reset: 'रीसेट',
  saveChanges: 'परिवर्तन सहेजें',
  qty: 'मात्रा',
  months: 'महीने',
  notifWarrantyExpiring: '3 एसेट्स की वारंटी समाप्त होने वाली है।',
  notifTasksCompleted: '2 मेंटेनेंस टास्क पूरे हुए।',
  notifNewProcurement: 'नई प्रोक्योरमेंट रिक्वेस्ट सबमिट हुई।'
};

const dictionaries: Record<Language, Dictionary> = { en, ta, hi };

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, fallback?: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('campusledger_language');
    if (stored === 'ta' || stored === 'hi' || stored === 'en') return stored;
    return 'en';
  });

  const value = useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage: (nextLanguage) => {
        setLanguage(nextLanguage);
        localStorage.setItem('campusledger_language', nextLanguage);
      },
      t: (key, fallback) => dictionaries[language][key] ?? dictionaries.en[key] ?? fallback ?? key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
